before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  directories:
  - node_modules
language: node_js
node_js:
- stable
script:
- npm run build:test
- npm run test:saucelabs
- ls -al coverage
- cat coverage/firefox/lcov.info | node_modules/.bin/coveralls
addons:
  hostname: karmalocal.com