language: node_js
node_js:
- stable
addons:
  hostname: karmalocal.com
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build:test
- npm run test:saucelabs
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: wlUOtef0e+zEib2MIKUwoV4sPNELN5A45IJhcF+12ArWvKJbRCKkkjQlYsgqU/Nhy8kQ8rbzdws7cQ5Pl9pnPXFKYU4PvA8gJgY19rnBEFIpwpcIL1y4EvTITvIKbRInIMnat9dVuWs/kOC+RmLx7h86d8fQq36AjDZ4Mh6RMrFjHuM55OV07xw+iDC5MN0Cw4IspvktqSE1HpBZ8bxX0Q0iymno4FVY9IPjVmjpuwFtNpBYAoyQjSiVmo5PAA+MkHSR0FG8rPTqFm49skpnDcrywrwn8CQU74PGOcOU0DGeBcKqwkoP2yrJ8ampAYNcAQWD698EzAVOo4ymfahCiUA6J/1nsVq4tZl5nmjYpkf+HcqPhbBIYp8PAkA4VqheuNNAnBDUpAVAn8bZP1wBRaBQDJKBslcnRCFGKUYygTMeGYpM41irczMkK9N4pJ+TdfyeYv2dxvHOyhh0CJlpNK0fHbzgBfPy2CIF7l38fylr5TCtEup43uTyfPe00FKC0ZehKaGa+MIwJPuU09yalFTUNZitlOVMKhSIOIVt6JQkqIW8Pzd8uG8HOesDyfScpo4GhpcLTn5Qz+Pm6q0qptMzktQKrlzLE4gXYwUwr491PmPc43qxyDMpOzAG8mdsLjgLxEyMiZv4y79Es/53ITkwoG6iTgNjnBWoo7cYDRQ=
  email: false
env:
  global:
  - secure: zCqYO7XYtLoJhUt03k6+fIbey8hOXYsMdtP7r+Oob+4kySGbyIqsBa7XQZAWj5pcdyjFNAyyC0AZR04c2qKVgSyYvpwtaTKJz3mT61cRYNOc1rUdNPMQAYuSqwundD25Vt7KbM+1Wn/o9ODvGt2wRczlsBDtqWY11tE2xwdojwSy6Sjqqx2Ng8oiS0IfwhkbGTIVVNOi2RkdNuauY3SoPr/pLRtvgY/jzGGm7zBwGWTUWItjMJJU0ybiCfPxVwuSjouAbw0BZgc5CwqZp7G6eRmROz1+lYn0PUW+QhNRlSMhC8+KyjzMy/MDY0dOL6qJMPK0MyOaPLAzSiH89OrsejqqnH2rgN9Xk4JX/q9zAP5xY/KJCZR8UHAe/mvdQbfUBZW41A1KzzGIp11/gu8pn4xusfy1FVfOOyu66GQgna69mpbJl6VMiCphp4fZsLoA2VEUnJu9IJu6q5vZl5J6kph7AK3gb2Y6NAfLaDOAt3PdBx/NRTK31P4LSE1m6BEEMIFr19TUTbLE0xJEnvSGe9C8FUYFwHZZVCJiwbXDirp5hGoGwx209+kkYDuTOgP9jAE97KOyzI7TSHJEFk5RkTncS8Q6EYi8nNbarcIi7A6W/AURaRrhzohk62EJpe3ZJQ0n1QzKwKu4YNM3ymydQgT0bqEyk8psqzN7rm+NAuM=
  - secure: uCveaRsenw2LG4HakIGGGgzYcqK0u+yqzkCO+cFkCAwJgEiWdxf+J1M6IaT94a0lr9XLSIT0UelVJ/Wlvj0RPy891fWPo1BnRaHeogeCwzyHZWbF3PTSIpEygJDTbjhHBwp36j4fyTbNRdhEDZm/4pVkbt/ifaaAf907JKrqrOvQmSJh4AbuN3FAlh6hKRV9iw7dOK3EltqAyWiq0/xsV3g8g99/0J2aO/csNdPzEVQOYZyf50XUfT+N2JEPaekZBq4FmHwgvpkRAbqv7GWPAJceVKOcpagwUIojb6FEGQhL4zvPTSkFU70yzAPigbshI7Z4Ko5fCTvXNYZoppsFUvsD3SpGHKRBLQj51Y6jZI2YuD/niQ7adhqSvM4kXK1brK47PqdhREtlK60vt/jwYyBjtLDWA3djZbsDfpB8O9YsGfhf6F3a9MJLcrvKfMKffAi0mdQV5F8PVs12WAcLAl87J/xUGEKvhQRCVyVbiC8j/QrtYaFPXDyZC1pMq7Ao/On3KUuiyH1Z1y1byN7bp5aF1TUE+4N+7JkCtQ8Gu44Yt7WYpQAEgORZUGunkvRbCMcOp45HvIo0ELaDd5uhja7wWk9IeUUC08LfPOViH996qPotaYYYPJmhwzwOeOWL7jB7iiTEbSsTMEB2yZsxSzeQG7oGTLCqfVQFBPAIz38=
